port: 7772
host: server
postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
quotes:
  - "Quote 1"
  - "Quote 2"
  - "Quote 3"
zerosCount: 20
ttl: 48h
randThreshold: 40
clientMaxCounter: 10000000
clientDelay: 1s
